sudo: required
language: python
os:
 - windows
python:
 - "3.5"
install:
 - pip install python-coveralls
 - pip install coverage
 - pip install nose
 - pip install codecov
script:
 - coverage run echo Coverage success
 - echo Test build passed
after_success:
 - codecov
 - coveralls